// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="synth_tb_synth_tb,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=90865,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1250,HLS_SYN_LUT=2869,HLS_VERSION=2021_2}" *)

module synth_tb (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_myarr_AWVALID,
        m_axi_myarr_AWREADY,
        m_axi_myarr_AWADDR,
        m_axi_myarr_AWID,
        m_axi_myarr_AWLEN,
        m_axi_myarr_AWSIZE,
        m_axi_myarr_AWBURST,
        m_axi_myarr_AWLOCK,
        m_axi_myarr_AWCACHE,
        m_axi_myarr_AWPROT,
        m_axi_myarr_AWQOS,
        m_axi_myarr_AWREGION,
        m_axi_myarr_AWUSER,
        m_axi_myarr_WVALID,
        m_axi_myarr_WREADY,
        m_axi_myarr_WDATA,
        m_axi_myarr_WSTRB,
        m_axi_myarr_WLAST,
        m_axi_myarr_WID,
        m_axi_myarr_WUSER,
        m_axi_myarr_ARVALID,
        m_axi_myarr_ARREADY,
        m_axi_myarr_ARADDR,
        m_axi_myarr_ARID,
        m_axi_myarr_ARLEN,
        m_axi_myarr_ARSIZE,
        m_axi_myarr_ARBURST,
        m_axi_myarr_ARLOCK,
        m_axi_myarr_ARCACHE,
        m_axi_myarr_ARPROT,
        m_axi_myarr_ARQOS,
        m_axi_myarr_ARREGION,
        m_axi_myarr_ARUSER,
        m_axi_myarr_RVALID,
        m_axi_myarr_RREADY,
        m_axi_myarr_RDATA,
        m_axi_myarr_RLAST,
        m_axi_myarr_RID,
        m_axi_myarr_RUSER,
        m_axi_myarr_RRESP,
        m_axi_myarr_BVALID,
        m_axi_myarr_BREADY,
        m_axi_myarr_BRESP,
        m_axi_myarr_BID,
        m_axi_myarr_BUSER,
        n,
        myarr_out,
        myarr_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;
parameter    C_M_AXI_MYARR_ID_WIDTH = 1;
parameter    C_M_AXI_MYARR_ADDR_WIDTH = 32;
parameter    C_M_AXI_MYARR_DATA_WIDTH = 32;
parameter    C_M_AXI_MYARR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MYARR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MYARR_WUSER_WIDTH = 1;
parameter    C_M_AXI_MYARR_RUSER_WIDTH = 1;
parameter    C_M_AXI_MYARR_BUSER_WIDTH = 1;
parameter    C_M_AXI_MYARR_TARGET_ADDR = 0;
parameter    C_M_AXI_MYARR_USER_VALUE = 0;
parameter    C_M_AXI_MYARR_PROT_VALUE = 0;
parameter    C_M_AXI_MYARR_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_MYARR_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_myarr_AWVALID;
input   m_axi_myarr_AWREADY;
output  [C_M_AXI_MYARR_ADDR_WIDTH - 1:0] m_axi_myarr_AWADDR;
output  [C_M_AXI_MYARR_ID_WIDTH - 1:0] m_axi_myarr_AWID;
output  [7:0] m_axi_myarr_AWLEN;
output  [2:0] m_axi_myarr_AWSIZE;
output  [1:0] m_axi_myarr_AWBURST;
output  [1:0] m_axi_myarr_AWLOCK;
output  [3:0] m_axi_myarr_AWCACHE;
output  [2:0] m_axi_myarr_AWPROT;
output  [3:0] m_axi_myarr_AWQOS;
output  [3:0] m_axi_myarr_AWREGION;
output  [C_M_AXI_MYARR_AWUSER_WIDTH - 1:0] m_axi_myarr_AWUSER;
output   m_axi_myarr_WVALID;
input   m_axi_myarr_WREADY;
output  [C_M_AXI_MYARR_DATA_WIDTH - 1:0] m_axi_myarr_WDATA;
output  [C_M_AXI_MYARR_WSTRB_WIDTH - 1:0] m_axi_myarr_WSTRB;
output   m_axi_myarr_WLAST;
output  [C_M_AXI_MYARR_ID_WIDTH - 1:0] m_axi_myarr_WID;
output  [C_M_AXI_MYARR_WUSER_WIDTH - 1:0] m_axi_myarr_WUSER;
output   m_axi_myarr_ARVALID;
input   m_axi_myarr_ARREADY;
output  [C_M_AXI_MYARR_ADDR_WIDTH - 1:0] m_axi_myarr_ARADDR;
output  [C_M_AXI_MYARR_ID_WIDTH - 1:0] m_axi_myarr_ARID;
output  [7:0] m_axi_myarr_ARLEN;
output  [2:0] m_axi_myarr_ARSIZE;
output  [1:0] m_axi_myarr_ARBURST;
output  [1:0] m_axi_myarr_ARLOCK;
output  [3:0] m_axi_myarr_ARCACHE;
output  [2:0] m_axi_myarr_ARPROT;
output  [3:0] m_axi_myarr_ARQOS;
output  [3:0] m_axi_myarr_ARREGION;
output  [C_M_AXI_MYARR_ARUSER_WIDTH - 1:0] m_axi_myarr_ARUSER;
input   m_axi_myarr_RVALID;
output   m_axi_myarr_RREADY;
input  [C_M_AXI_MYARR_DATA_WIDTH - 1:0] m_axi_myarr_RDATA;
input   m_axi_myarr_RLAST;
input  [C_M_AXI_MYARR_ID_WIDTH - 1:0] m_axi_myarr_RID;
input  [C_M_AXI_MYARR_RUSER_WIDTH - 1:0] m_axi_myarr_RUSER;
input  [1:0] m_axi_myarr_RRESP;
input   m_axi_myarr_BVALID;
output   m_axi_myarr_BREADY;
input  [1:0] m_axi_myarr_BRESP;
input  [C_M_AXI_MYARR_ID_WIDTH - 1:0] m_axi_myarr_BID;
input  [C_M_AXI_MYARR_BUSER_WIDTH - 1:0] m_axi_myarr_BUSER;
input  [31:0] n;
output  [31:0] myarr_out;
output   myarr_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    myarr_blk_n_AW;
reg    myarr_blk_n_B;
wire    ap_CS_fsm_state8;
reg    myarr_blk_n_AR;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state6;
wire  signed [31:0] sub_i_fu_171_p2;
reg  signed [31:0] sub_i_reg_374;
reg   [0:0] tmp_2_reg_381;
wire   [0:0] icmp_ln16_fu_204_p2;
reg   [0:0] icmp_ln16_reg_385;
wire    ap_CS_fsm_state7;
wire   [32:0] add_ln16_1_fu_210_p2;
reg   [32:0] add_ln16_1_reg_390;
wire   [0:0] icmp_ln16_1_fu_216_p2;
reg   [0:0] icmp_ln16_1_reg_395;
wire   [0:0] cmp_i3_fu_222_p2;
reg   [0:0] cmp_i3_reg_400;
wire   [63:0] add_ln16_4_fu_291_p2;
reg   [63:0] add_ln16_4_reg_404;
wire   [63:0] add_ln16_5_fu_297_p2;
reg   [63:0] add_ln16_5_reg_409;
wire   [31:0] and_ln_fu_313_p3;
reg   [31:0] and_ln_reg_414;
wire   [31:0] and_ln1_fu_331_p3;
reg   [31:0] and_ln1_reg_419;
wire   [0:0] icmp_ln16_2_fu_347_p2;
reg   [0:0] icmp_ln16_2_reg_424;
wire    ap_CS_fsm_state13;
reg   [0:0] ap_phi_mux_is_sorted_phi_fu_129_p4;
wire   [30:0] trunc_ln16_1_fu_352_p1;
reg   [30:0] trunc_ln16_1_reg_428;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_done;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_idle;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_ready;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWVALID;
wire   [31:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWADDR;
wire   [0:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWID;
wire   [31:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWLEN;
wire   [2:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWSIZE;
wire   [1:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWBURST;
wire   [1:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWLOCK;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWCACHE;
wire   [2:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWPROT;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWQOS;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWREGION;
wire   [0:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWUSER;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WVALID;
wire   [31:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WDATA;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WSTRB;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WLAST;
wire   [0:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WID;
wire   [0:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WUSER;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARVALID;
wire   [31:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARADDR;
wire   [0:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARID;
wire   [31:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARLEN;
wire   [2:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARSIZE;
wire   [1:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARBURST;
wire   [1:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARLOCK;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARCACHE;
wire   [2:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARPROT;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARQOS;
wire   [3:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARREGION;
wire   [0:0] grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARUSER;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_RREADY;
wire    grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_BREADY;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_ap_start;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_ap_done;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_ap_idle;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_ap_ready;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWVALID;
wire   [31:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWADDR;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWID;
wire   [31:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWLEN;
wire   [2:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWSIZE;
wire   [1:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWBURST;
wire   [1:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWLOCK;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWCACHE;
wire   [2:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWPROT;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWQOS;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWREGION;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWUSER;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WVALID;
wire   [31:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WDATA;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WSTRB;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WLAST;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WID;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WUSER;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARVALID;
wire   [31:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARADDR;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARID;
wire   [31:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARLEN;
wire   [2:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARSIZE;
wire   [1:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARBURST;
wire   [1:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARLOCK;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARCACHE;
wire   [2:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARPROT;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARQOS;
wire   [3:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARREGION;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARUSER;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_RREADY;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_BREADY;
wire   [0:0] grp_synth_tb_Pipeline_for_odd_fu_142_is_sorted_1_out;
wire    grp_synth_tb_Pipeline_for_odd_fu_142_is_sorted_1_out_ap_vld;
wire    grp_synth_tb_Pipeline_for_even_fu_151_ap_start;
wire    grp_synth_tb_Pipeline_for_even_fu_151_ap_done;
wire    grp_synth_tb_Pipeline_for_even_fu_151_ap_idle;
wire    grp_synth_tb_Pipeline_for_even_fu_151_ap_ready;
wire    grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWVALID;
wire   [31:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWADDR;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWID;
wire   [31:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWLEN;
wire   [2:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWSIZE;
wire   [1:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWBURST;
wire   [1:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWLOCK;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWCACHE;
wire   [2:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWPROT;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWQOS;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWREGION;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWUSER;
wire    grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WVALID;
wire   [31:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WDATA;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WSTRB;
wire    grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WLAST;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WID;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WUSER;
wire    grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARVALID;
wire   [31:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARADDR;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARID;
wire   [31:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARLEN;
wire   [2:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARSIZE;
wire   [1:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARBURST;
wire   [1:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARLOCK;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARCACHE;
wire   [2:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARPROT;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARQOS;
wire   [3:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARREGION;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARUSER;
wire    grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_RREADY;
wire    grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_BREADY;
wire   [0:0] grp_synth_tb_Pipeline_for_even_fu_151_is_sorted_4_out;
wire    grp_synth_tb_Pipeline_for_even_fu_151_is_sorted_4_out_ap_vld;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_ap_done;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_ap_idle;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_ap_ready;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWVALID;
wire   [31:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWADDR;
wire   [0:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWID;
wire   [31:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWLEN;
wire   [2:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWSIZE;
wire   [1:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWBURST;
wire   [1:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWLOCK;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWCACHE;
wire   [2:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWPROT;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWQOS;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWREGION;
wire   [0:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWUSER;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WVALID;
wire   [31:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WDATA;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WSTRB;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WLAST;
wire   [0:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WID;
wire   [0:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WUSER;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARVALID;
wire   [31:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARADDR;
wire   [0:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARID;
wire   [31:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARLEN;
wire   [2:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARSIZE;
wire   [1:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARBURST;
wire   [1:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARLOCK;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARCACHE;
wire   [2:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARPROT;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARQOS;
wire   [3:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARREGION;
wire   [0:0] grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARUSER;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_RREADY;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_BREADY;
wire   [31:0] grp_synth_tb_Pipeline_read_sorted_fu_162_myarr_out;
wire    grp_synth_tb_Pipeline_read_sorted_fu_162_myarr_out_ap_vld;
reg    myarr_AWVALID;
wire    myarr_AWREADY;
reg   [31:0] myarr_AWADDR;
reg   [0:0] myarr_AWID;
reg   [31:0] myarr_AWLEN;
reg   [2:0] myarr_AWSIZE;
reg   [1:0] myarr_AWBURST;
reg   [1:0] myarr_AWLOCK;
reg   [3:0] myarr_AWCACHE;
reg   [2:0] myarr_AWPROT;
reg   [3:0] myarr_AWQOS;
reg   [3:0] myarr_AWREGION;
reg   [0:0] myarr_AWUSER;
reg    myarr_WVALID;
wire    myarr_WREADY;
reg   [31:0] myarr_WDATA;
reg   [3:0] myarr_WSTRB;
reg    myarr_WLAST;
reg   [0:0] myarr_WID;
reg   [0:0] myarr_WUSER;
reg    myarr_ARVALID;
wire    myarr_ARREADY;
reg   [31:0] myarr_ARADDR;
reg   [0:0] myarr_ARID;
reg   [31:0] myarr_ARLEN;
reg   [2:0] myarr_ARSIZE;
reg   [1:0] myarr_ARBURST;
reg   [1:0] myarr_ARLOCK;
reg   [3:0] myarr_ARCACHE;
reg   [2:0] myarr_ARPROT;
reg   [3:0] myarr_ARQOS;
reg   [3:0] myarr_ARREGION;
reg   [0:0] myarr_ARUSER;
wire    myarr_RVALID;
reg    myarr_RREADY;
wire   [31:0] myarr_RDATA;
wire    myarr_RLAST;
wire   [0:0] myarr_RID;
wire   [8:0] myarr_RFIFONUM;
wire   [0:0] myarr_RUSER;
wire   [1:0] myarr_RRESP;
wire    myarr_BVALID;
reg    myarr_BREADY;
wire   [1:0] myarr_BRESP;
wire   [0:0] myarr_BID;
wire   [0:0] myarr_BUSER;
reg   [0:0] ap_phi_mux_is_sorted_1_phi_fu_118_p4;
reg   [0:0] is_sorted_1_reg_114;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state9;
reg   [0:0] is_sorted_reg_126;
reg    grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_synth_tb_Pipeline_for_odd_fu_142_ap_start_reg;
reg   [21:0] ap_NS_fsm;
wire    ap_NS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_synth_tb_Pipeline_for_even_fu_151_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start_reg;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire  signed [32:0] sext_ln16_fu_185_p1;
wire   [32:0] add_ln16_fu_188_p2;
wire   [30:0] tmp_3_fu_194_p4;
wire   [32:0] select_ln16_fu_227_p3;
wire   [31:0] trunc_ln16_2_fu_233_p4;
wire  signed [62:0] sext_ln16_1_fu_243_p1;
wire   [31:0] trunc_ln16_fu_251_p1;
wire   [31:0] select_ln16_1_fu_261_p3;
wire   [30:0] trunc_ln16_3_fu_267_p4;
wire  signed [62:0] sext_ln16_2_fu_277_p1;
wire   [63:0] zext_ln16_fu_247_p1;
wire   [63:0] zext_ln16_1_fu_281_p1;
wire   [31:0] add_ln16_2_fu_255_p2;
wire   [30:0] tmp_fu_303_p4;
wire   [31:0] add_ln16_3_fu_285_p2;
wire   [30:0] tmp_1_fu_321_p4;
reg    ap_block_state22_on_subcall_done;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start_reg = 1'b0;
#0 grp_synth_tb_Pipeline_for_odd_fu_142_ap_start_reg = 1'b0;
#0 grp_synth_tb_Pipeline_for_even_fu_151_ap_start_reg = 1'b0;
#0 grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start_reg = 1'b0;
end

synth_tb_synth_tb_Pipeline_fill_unsorted grp_synth_tb_Pipeline_fill_unsorted_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start),
    .ap_done(grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_done),
    .ap_idle(grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_idle),
    .ap_ready(grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_ready),
    .m_axi_myarr_AWVALID(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWVALID),
    .m_axi_myarr_AWREADY(myarr_AWREADY),
    .m_axi_myarr_AWADDR(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWADDR),
    .m_axi_myarr_AWID(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWID),
    .m_axi_myarr_AWLEN(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWLEN),
    .m_axi_myarr_AWSIZE(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWSIZE),
    .m_axi_myarr_AWBURST(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWBURST),
    .m_axi_myarr_AWLOCK(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWLOCK),
    .m_axi_myarr_AWCACHE(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWCACHE),
    .m_axi_myarr_AWPROT(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWPROT),
    .m_axi_myarr_AWQOS(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWQOS),
    .m_axi_myarr_AWREGION(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWREGION),
    .m_axi_myarr_AWUSER(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWUSER),
    .m_axi_myarr_WVALID(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WVALID),
    .m_axi_myarr_WREADY(myarr_WREADY),
    .m_axi_myarr_WDATA(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WDATA),
    .m_axi_myarr_WSTRB(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WSTRB),
    .m_axi_myarr_WLAST(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WLAST),
    .m_axi_myarr_WID(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WID),
    .m_axi_myarr_WUSER(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WUSER),
    .m_axi_myarr_ARVALID(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARVALID),
    .m_axi_myarr_ARREADY(1'b0),
    .m_axi_myarr_ARADDR(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARADDR),
    .m_axi_myarr_ARID(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARID),
    .m_axi_myarr_ARLEN(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARLEN),
    .m_axi_myarr_ARSIZE(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARSIZE),
    .m_axi_myarr_ARBURST(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARBURST),
    .m_axi_myarr_ARLOCK(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARLOCK),
    .m_axi_myarr_ARCACHE(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARCACHE),
    .m_axi_myarr_ARPROT(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARPROT),
    .m_axi_myarr_ARQOS(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARQOS),
    .m_axi_myarr_ARREGION(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARREGION),
    .m_axi_myarr_ARUSER(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_ARUSER),
    .m_axi_myarr_RVALID(1'b0),
    .m_axi_myarr_RREADY(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_RREADY),
    .m_axi_myarr_RDATA(32'd0),
    .m_axi_myarr_RLAST(1'b0),
    .m_axi_myarr_RID(1'd0),
    .m_axi_myarr_RFIFONUM(9'd0),
    .m_axi_myarr_RUSER(1'd0),
    .m_axi_myarr_RRESP(2'd0),
    .m_axi_myarr_BVALID(myarr_BVALID),
    .m_axi_myarr_BREADY(grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_BREADY),
    .m_axi_myarr_BRESP(myarr_BRESP),
    .m_axi_myarr_BID(myarr_BID),
    .m_axi_myarr_BUSER(myarr_BUSER)
);

synth_tb_synth_tb_Pipeline_for_odd grp_synth_tb_Pipeline_for_odd_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_synth_tb_Pipeline_for_odd_fu_142_ap_start),
    .ap_done(grp_synth_tb_Pipeline_for_odd_fu_142_ap_done),
    .ap_idle(grp_synth_tb_Pipeline_for_odd_fu_142_ap_idle),
    .ap_ready(grp_synth_tb_Pipeline_for_odd_fu_142_ap_ready),
    .m_axi_myarr_AWVALID(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWVALID),
    .m_axi_myarr_AWREADY(myarr_AWREADY),
    .m_axi_myarr_AWADDR(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWADDR),
    .m_axi_myarr_AWID(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWID),
    .m_axi_myarr_AWLEN(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWLEN),
    .m_axi_myarr_AWSIZE(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWSIZE),
    .m_axi_myarr_AWBURST(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWBURST),
    .m_axi_myarr_AWLOCK(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWLOCK),
    .m_axi_myarr_AWCACHE(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWCACHE),
    .m_axi_myarr_AWPROT(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWPROT),
    .m_axi_myarr_AWQOS(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWQOS),
    .m_axi_myarr_AWREGION(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWREGION),
    .m_axi_myarr_AWUSER(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWUSER),
    .m_axi_myarr_WVALID(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WVALID),
    .m_axi_myarr_WREADY(myarr_WREADY),
    .m_axi_myarr_WDATA(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WDATA),
    .m_axi_myarr_WSTRB(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WSTRB),
    .m_axi_myarr_WLAST(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WLAST),
    .m_axi_myarr_WID(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WID),
    .m_axi_myarr_WUSER(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WUSER),
    .m_axi_myarr_ARVALID(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARVALID),
    .m_axi_myarr_ARREADY(myarr_ARREADY),
    .m_axi_myarr_ARADDR(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARADDR),
    .m_axi_myarr_ARID(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARID),
    .m_axi_myarr_ARLEN(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARLEN),
    .m_axi_myarr_ARSIZE(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARSIZE),
    .m_axi_myarr_ARBURST(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARBURST),
    .m_axi_myarr_ARLOCK(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARLOCK),
    .m_axi_myarr_ARCACHE(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARCACHE),
    .m_axi_myarr_ARPROT(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARPROT),
    .m_axi_myarr_ARQOS(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARQOS),
    .m_axi_myarr_ARREGION(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARREGION),
    .m_axi_myarr_ARUSER(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARUSER),
    .m_axi_myarr_RVALID(myarr_RVALID),
    .m_axi_myarr_RREADY(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_RREADY),
    .m_axi_myarr_RDATA(myarr_RDATA),
    .m_axi_myarr_RLAST(myarr_RLAST),
    .m_axi_myarr_RID(myarr_RID),
    .m_axi_myarr_RFIFONUM(myarr_RFIFONUM),
    .m_axi_myarr_RUSER(myarr_RUSER),
    .m_axi_myarr_RRESP(myarr_RRESP),
    .m_axi_myarr_BVALID(myarr_BVALID),
    .m_axi_myarr_BREADY(grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_BREADY),
    .m_axi_myarr_BRESP(myarr_BRESP),
    .m_axi_myarr_BID(myarr_BID),
    .m_axi_myarr_BUSER(myarr_BUSER),
    .add_ln16_4(add_ln16_4_reg_404),
    .and_ln(and_ln_reg_414),
    .is_sorted_1_out(grp_synth_tb_Pipeline_for_odd_fu_142_is_sorted_1_out),
    .is_sorted_1_out_ap_vld(grp_synth_tb_Pipeline_for_odd_fu_142_is_sorted_1_out_ap_vld)
);

synth_tb_synth_tb_Pipeline_for_even grp_synth_tb_Pipeline_for_even_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_synth_tb_Pipeline_for_even_fu_151_ap_start),
    .ap_done(grp_synth_tb_Pipeline_for_even_fu_151_ap_done),
    .ap_idle(grp_synth_tb_Pipeline_for_even_fu_151_ap_idle),
    .ap_ready(grp_synth_tb_Pipeline_for_even_fu_151_ap_ready),
    .m_axi_myarr_AWVALID(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWVALID),
    .m_axi_myarr_AWREADY(myarr_AWREADY),
    .m_axi_myarr_AWADDR(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWADDR),
    .m_axi_myarr_AWID(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWID),
    .m_axi_myarr_AWLEN(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWLEN),
    .m_axi_myarr_AWSIZE(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWSIZE),
    .m_axi_myarr_AWBURST(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWBURST),
    .m_axi_myarr_AWLOCK(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWLOCK),
    .m_axi_myarr_AWCACHE(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWCACHE),
    .m_axi_myarr_AWPROT(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWPROT),
    .m_axi_myarr_AWQOS(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWQOS),
    .m_axi_myarr_AWREGION(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWREGION),
    .m_axi_myarr_AWUSER(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWUSER),
    .m_axi_myarr_WVALID(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WVALID),
    .m_axi_myarr_WREADY(myarr_WREADY),
    .m_axi_myarr_WDATA(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WDATA),
    .m_axi_myarr_WSTRB(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WSTRB),
    .m_axi_myarr_WLAST(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WLAST),
    .m_axi_myarr_WID(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WID),
    .m_axi_myarr_WUSER(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WUSER),
    .m_axi_myarr_ARVALID(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARVALID),
    .m_axi_myarr_ARREADY(myarr_ARREADY),
    .m_axi_myarr_ARADDR(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARADDR),
    .m_axi_myarr_ARID(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARID),
    .m_axi_myarr_ARLEN(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARLEN),
    .m_axi_myarr_ARSIZE(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARSIZE),
    .m_axi_myarr_ARBURST(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARBURST),
    .m_axi_myarr_ARLOCK(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARLOCK),
    .m_axi_myarr_ARCACHE(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARCACHE),
    .m_axi_myarr_ARPROT(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARPROT),
    .m_axi_myarr_ARQOS(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARQOS),
    .m_axi_myarr_ARREGION(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARREGION),
    .m_axi_myarr_ARUSER(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARUSER),
    .m_axi_myarr_RVALID(myarr_RVALID),
    .m_axi_myarr_RREADY(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_RREADY),
    .m_axi_myarr_RDATA(myarr_RDATA),
    .m_axi_myarr_RLAST(myarr_RLAST),
    .m_axi_myarr_RID(myarr_RID),
    .m_axi_myarr_RFIFONUM(myarr_RFIFONUM),
    .m_axi_myarr_RUSER(myarr_RUSER),
    .m_axi_myarr_RRESP(myarr_RRESP),
    .m_axi_myarr_BVALID(myarr_BVALID),
    .m_axi_myarr_BREADY(grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_BREADY),
    .m_axi_myarr_BRESP(myarr_BRESP),
    .m_axi_myarr_BID(myarr_BID),
    .m_axi_myarr_BUSER(myarr_BUSER),
    .is_sorted_2(is_sorted_1_reg_114),
    .add_ln16_5(add_ln16_5_reg_409),
    .and_ln1(and_ln1_reg_419),
    .is_sorted_4_out(grp_synth_tb_Pipeline_for_even_fu_151_is_sorted_4_out),
    .is_sorted_4_out_ap_vld(grp_synth_tb_Pipeline_for_even_fu_151_is_sorted_4_out_ap_vld)
);

synth_tb_synth_tb_Pipeline_read_sorted grp_synth_tb_Pipeline_read_sorted_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start),
    .ap_done(grp_synth_tb_Pipeline_read_sorted_fu_162_ap_done),
    .ap_idle(grp_synth_tb_Pipeline_read_sorted_fu_162_ap_idle),
    .ap_ready(grp_synth_tb_Pipeline_read_sorted_fu_162_ap_ready),
    .m_axi_myarr_AWVALID(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWVALID),
    .m_axi_myarr_AWREADY(1'b0),
    .m_axi_myarr_AWADDR(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWADDR),
    .m_axi_myarr_AWID(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWID),
    .m_axi_myarr_AWLEN(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWLEN),
    .m_axi_myarr_AWSIZE(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWSIZE),
    .m_axi_myarr_AWBURST(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWBURST),
    .m_axi_myarr_AWLOCK(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWLOCK),
    .m_axi_myarr_AWCACHE(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWCACHE),
    .m_axi_myarr_AWPROT(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWPROT),
    .m_axi_myarr_AWQOS(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWQOS),
    .m_axi_myarr_AWREGION(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWREGION),
    .m_axi_myarr_AWUSER(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_AWUSER),
    .m_axi_myarr_WVALID(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WVALID),
    .m_axi_myarr_WREADY(1'b0),
    .m_axi_myarr_WDATA(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WDATA),
    .m_axi_myarr_WSTRB(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WSTRB),
    .m_axi_myarr_WLAST(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WLAST),
    .m_axi_myarr_WID(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WID),
    .m_axi_myarr_WUSER(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_WUSER),
    .m_axi_myarr_ARVALID(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARVALID),
    .m_axi_myarr_ARREADY(myarr_ARREADY),
    .m_axi_myarr_ARADDR(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARADDR),
    .m_axi_myarr_ARID(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARID),
    .m_axi_myarr_ARLEN(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARLEN),
    .m_axi_myarr_ARSIZE(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARSIZE),
    .m_axi_myarr_ARBURST(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARBURST),
    .m_axi_myarr_ARLOCK(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARLOCK),
    .m_axi_myarr_ARCACHE(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARCACHE),
    .m_axi_myarr_ARPROT(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARPROT),
    .m_axi_myarr_ARQOS(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARQOS),
    .m_axi_myarr_ARREGION(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARREGION),
    .m_axi_myarr_ARUSER(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARUSER),
    .m_axi_myarr_RVALID(myarr_RVALID),
    .m_axi_myarr_RREADY(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_RREADY),
    .m_axi_myarr_RDATA(myarr_RDATA),
    .m_axi_myarr_RLAST(myarr_RLAST),
    .m_axi_myarr_RID(myarr_RID),
    .m_axi_myarr_RFIFONUM(myarr_RFIFONUM),
    .m_axi_myarr_RUSER(myarr_RUSER),
    .m_axi_myarr_RRESP(myarr_RRESP),
    .m_axi_myarr_BVALID(1'b0),
    .m_axi_myarr_BREADY(grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_BREADY),
    .m_axi_myarr_BRESP(2'd0),
    .m_axi_myarr_BID(1'd0),
    .m_axi_myarr_BUSER(1'd0),
    .trunc_ln16_4(trunc_ln16_1_reg_428),
    .myarr_out(grp_synth_tb_Pipeline_read_sorted_fu_162_myarr_out),
    .myarr_out_ap_vld(grp_synth_tb_Pipeline_read_sorted_fu_162_myarr_out_ap_vld)
);

synth_tb_myarr_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MYARR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MYARR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MYARR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MYARR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MYARR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MYARR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MYARR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MYARR_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_MYARR_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_MYARR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MYARR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MYARR_CACHE_VALUE ))
myarr_m_axi_U(
    .AWVALID(m_axi_myarr_AWVALID),
    .AWREADY(m_axi_myarr_AWREADY),
    .AWADDR(m_axi_myarr_AWADDR),
    .AWID(m_axi_myarr_AWID),
    .AWLEN(m_axi_myarr_AWLEN),
    .AWSIZE(m_axi_myarr_AWSIZE),
    .AWBURST(m_axi_myarr_AWBURST),
    .AWLOCK(m_axi_myarr_AWLOCK),
    .AWCACHE(m_axi_myarr_AWCACHE),
    .AWPROT(m_axi_myarr_AWPROT),
    .AWQOS(m_axi_myarr_AWQOS),
    .AWREGION(m_axi_myarr_AWREGION),
    .AWUSER(m_axi_myarr_AWUSER),
    .WVALID(m_axi_myarr_WVALID),
    .WREADY(m_axi_myarr_WREADY),
    .WDATA(m_axi_myarr_WDATA),
    .WSTRB(m_axi_myarr_WSTRB),
    .WLAST(m_axi_myarr_WLAST),
    .WID(m_axi_myarr_WID),
    .WUSER(m_axi_myarr_WUSER),
    .ARVALID(m_axi_myarr_ARVALID),
    .ARREADY(m_axi_myarr_ARREADY),
    .ARADDR(m_axi_myarr_ARADDR),
    .ARID(m_axi_myarr_ARID),
    .ARLEN(m_axi_myarr_ARLEN),
    .ARSIZE(m_axi_myarr_ARSIZE),
    .ARBURST(m_axi_myarr_ARBURST),
    .ARLOCK(m_axi_myarr_ARLOCK),
    .ARCACHE(m_axi_myarr_ARCACHE),
    .ARPROT(m_axi_myarr_ARPROT),
    .ARQOS(m_axi_myarr_ARQOS),
    .ARREGION(m_axi_myarr_ARREGION),
    .ARUSER(m_axi_myarr_ARUSER),
    .RVALID(m_axi_myarr_RVALID),
    .RREADY(m_axi_myarr_RREADY),
    .RDATA(m_axi_myarr_RDATA),
    .RLAST(m_axi_myarr_RLAST),
    .RID(m_axi_myarr_RID),
    .RUSER(m_axi_myarr_RUSER),
    .RRESP(m_axi_myarr_RRESP),
    .BVALID(m_axi_myarr_BVALID),
    .BREADY(m_axi_myarr_BREADY),
    .BRESP(m_axi_myarr_BRESP),
    .BID(m_axi_myarr_BID),
    .BUSER(m_axi_myarr_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(myarr_ARVALID),
    .I_ARREADY(myarr_ARREADY),
    .I_ARADDR(myarr_ARADDR),
    .I_ARID(myarr_ARID),
    .I_ARLEN(myarr_ARLEN),
    .I_ARSIZE(myarr_ARSIZE),
    .I_ARLOCK(myarr_ARLOCK),
    .I_ARCACHE(myarr_ARCACHE),
    .I_ARQOS(myarr_ARQOS),
    .I_ARPROT(myarr_ARPROT),
    .I_ARUSER(myarr_ARUSER),
    .I_ARBURST(myarr_ARBURST),
    .I_ARREGION(myarr_ARREGION),
    .I_RVALID(myarr_RVALID),
    .I_RREADY(myarr_RREADY),
    .I_RDATA(myarr_RDATA),
    .I_RFIFONUM(myarr_RFIFONUM),
    .I_RID(myarr_RID),
    .I_RUSER(myarr_RUSER),
    .I_RRESP(myarr_RRESP),
    .I_RLAST(myarr_RLAST),
    .I_AWVALID(myarr_AWVALID),
    .I_AWREADY(myarr_AWREADY),
    .I_AWADDR(myarr_AWADDR),
    .I_AWID(myarr_AWID),
    .I_AWLEN(myarr_AWLEN),
    .I_AWSIZE(myarr_AWSIZE),
    .I_AWLOCK(myarr_AWLOCK),
    .I_AWCACHE(myarr_AWCACHE),
    .I_AWQOS(myarr_AWQOS),
    .I_AWPROT(myarr_AWPROT),
    .I_AWUSER(myarr_AWUSER),
    .I_AWBURST(myarr_AWBURST),
    .I_AWREGION(myarr_AWREGION),
    .I_WVALID(myarr_WVALID),
    .I_WREADY(myarr_WREADY),
    .I_WDATA(myarr_WDATA),
    .I_WID(myarr_WID),
    .I_WUSER(myarr_WUSER),
    .I_WLAST(myarr_WLAST),
    .I_WSTRB(myarr_WSTRB),
    .I_BVALID(myarr_BVALID),
    .I_BREADY(myarr_BREADY),
    .I_BRESP(myarr_BRESP),
    .I_BID(myarr_BID),
    .I_BUSER(myarr_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_ready == 1'b1)) begin
            grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_synth_tb_Pipeline_for_even_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0))) begin
            grp_synth_tb_Pipeline_for_even_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_synth_tb_Pipeline_for_even_fu_151_ap_ready == 1'b1)) begin
            grp_synth_tb_Pipeline_for_even_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_synth_tb_Pipeline_for_odd_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state9) & (((1'b1 == ap_CS_fsm_state13) & (cmp_i3_reg_400 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (cmp_i3_fu_222_p2 == 1'd1))))) begin
            grp_synth_tb_Pipeline_for_odd_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_synth_tb_Pipeline_for_odd_fu_142_ap_ready == 1'b1)) begin
            grp_synth_tb_Pipeline_for_odd_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_synth_tb_Pipeline_read_sorted_fu_162_ap_ready == 1'b1)) begin
            grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd0))) begin
        is_sorted_1_reg_114 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state11) & (cmp_i3_reg_400 == 1'd1))) begin
        is_sorted_1_reg_114 <= grp_synth_tb_Pipeline_for_odd_fu_142_is_sorted_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd1))) begin
        is_sorted_reg_126 <= ap_phi_mux_is_sorted_1_phi_fu_118_p4;
    end else if (((1'b1 == ap_CS_fsm_state13) & (tmp_2_reg_381 == 1'd0))) begin
        is_sorted_reg_126 <= grp_synth_tb_Pipeline_for_even_fu_151_is_sorted_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln16_1_reg_390 <= add_ln16_1_fu_210_p2;
        icmp_ln16_1_reg_395 <= icmp_ln16_1_fu_216_p2;
        icmp_ln16_reg_385 <= icmp_ln16_fu_204_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln16_4_reg_404 <= add_ln16_4_fu_291_p2;
        add_ln16_5_reg_409 <= add_ln16_5_fu_297_p2;
        and_ln1_reg_419[31 : 1] <= and_ln1_fu_331_p3[31 : 1];
        and_ln_reg_414[31 : 1] <= and_ln_fu_313_p3[31 : 1];
        cmp_i3_reg_400 <= cmp_i3_fu_222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (ap_phi_mux_is_sorted_phi_fu_129_p4 == 1'd1))) begin
        icmp_ln16_2_reg_424 <= icmp_ln16_2_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_i_reg_374 <= sub_i_fu_171_p2;
        tmp_2_reg_381 <= sub_i_fu_171_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        trunc_ln16_1_reg_428 <= trunc_ln16_1_fu_352_p1;
    end
end

always @ (*) begin
    if ((grp_synth_tb_Pipeline_for_odd_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_synth_tb_Pipeline_for_even_fu_151_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((myarr_ARREADY == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((myarr_AWREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state22_on_subcall_done)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((myarr_BVALID == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state22_on_subcall_done) & (1'b1 == ap_CS_fsm_state22))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (cmp_i3_reg_400 == 1'd1))) begin
        ap_phi_mux_is_sorted_1_phi_fu_118_p4 = grp_synth_tb_Pipeline_for_odd_fu_142_is_sorted_1_out;
    end else begin
        ap_phi_mux_is_sorted_1_phi_fu_118_p4 = is_sorted_1_reg_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_2_reg_381 == 1'd0))) begin
        ap_phi_mux_is_sorted_phi_fu_129_p4 = grp_synth_tb_Pipeline_for_even_fu_151_is_sorted_4_out;
    end else begin
        ap_phi_mux_is_sorted_phi_fu_129_p4 = is_sorted_reg_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state22_on_subcall_done) & (1'b1 == ap_CS_fsm_state22))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (myarr_ARREADY == 1'b1))) begin
        myarr_ARADDR = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARADDR = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARADDR = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARADDR = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARADDR;
    end else begin
        myarr_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARBURST = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARBURST = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARBURST = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARBURST;
    end else begin
        myarr_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARCACHE = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARCACHE = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARCACHE = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARCACHE;
    end else begin
        myarr_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARID = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARID;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARID = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARID;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARID = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARID;
    end else begin
        myarr_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (myarr_ARREADY == 1'b1))) begin
        myarr_ARLEN = n;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARLEN = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARLEN = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARLEN = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARLEN;
    end else begin
        myarr_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARLOCK = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARLOCK = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARLOCK = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARLOCK;
    end else begin
        myarr_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARPROT = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARPROT = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARPROT = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARPROT;
    end else begin
        myarr_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARQOS = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARQOS = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARQOS = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARQOS;
    end else begin
        myarr_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARREGION = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARREGION = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARREGION = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARREGION;
    end else begin
        myarr_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARSIZE = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARSIZE = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARSIZE = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARSIZE;
    end else begin
        myarr_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARUSER = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARUSER = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARUSER = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARUSER;
    end else begin
        myarr_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (myarr_ARREADY == 1'b1))) begin
        myarr_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_ARVALID = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_ARVALID = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_ARVALID = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_ARVALID;
    end else begin
        myarr_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((myarr_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        myarr_AWADDR = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWADDR = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWADDR = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWADDR = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWADDR;
    end else begin
        myarr_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWBURST = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWBURST;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWBURST = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWBURST;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWBURST = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWBURST;
    end else begin
        myarr_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWCACHE = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWCACHE;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWCACHE = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWCACHE;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWCACHE = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWCACHE;
    end else begin
        myarr_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWID = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWID;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWID = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWID;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWID = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWID;
    end else begin
        myarr_AWID = 1'd0;
    end
end

always @ (*) begin
    if ((~((myarr_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        myarr_AWLEN = 32'd100;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWLEN = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWLEN = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWLEN = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWLEN;
    end else begin
        myarr_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWLOCK = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWLOCK;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWLOCK = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWLOCK;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWLOCK = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWLOCK;
    end else begin
        myarr_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWPROT = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWPROT;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWPROT = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWPROT;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWPROT = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWPROT;
    end else begin
        myarr_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWQOS = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWQOS;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWQOS = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWQOS;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWQOS = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWQOS;
    end else begin
        myarr_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWREGION = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWREGION;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWREGION = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWREGION;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWREGION = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWREGION;
    end else begin
        myarr_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWSIZE = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWSIZE;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWSIZE = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWSIZE;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWSIZE = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWSIZE;
    end else begin
        myarr_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWUSER = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWUSER;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWUSER = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWUSER;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWUSER = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWUSER;
    end else begin
        myarr_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((myarr_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        myarr_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_AWVALID = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_AWVALID = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_AWVALID = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_AWVALID;
    end else begin
        myarr_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (myarr_BVALID == 1'b1))) begin
        myarr_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_BREADY = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_BREADY = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_BREADY = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_BREADY;
    end else begin
        myarr_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state22) & (icmp_ln16_2_reg_424 == 1'd1)))) begin
        myarr_RREADY = grp_synth_tb_Pipeline_read_sorted_fu_162_m_axi_myarr_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_RREADY = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_RREADY = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_RREADY;
    end else begin
        myarr_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_WDATA = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_WDATA = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_WDATA = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WDATA;
    end else begin
        myarr_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_WID = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WID;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_WID = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WID;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_WID = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WID;
    end else begin
        myarr_WID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_WLAST = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WLAST;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_WLAST = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WLAST;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_WLAST = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WLAST;
    end else begin
        myarr_WLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_WSTRB = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_WSTRB = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_WSTRB = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WSTRB;
    end else begin
        myarr_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_WUSER = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WUSER;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_WUSER = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WUSER;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_WUSER = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WUSER;
    end else begin
        myarr_WUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd0)))) begin
        myarr_WVALID = grp_synth_tb_Pipeline_for_even_fu_151_m_axi_myarr_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd1)))) begin
        myarr_WVALID = grp_synth_tb_Pipeline_for_odd_fu_142_m_axi_myarr_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        myarr_WVALID = grp_synth_tb_Pipeline_fill_unsorted_fu_136_m_axi_myarr_WVALID;
    end else begin
        myarr_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        myarr_blk_n_AR = m_axi_myarr_ARREADY;
    end else begin
        myarr_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        myarr_blk_n_AW = m_axi_myarr_AWREADY;
    end else begin
        myarr_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        myarr_blk_n_B = m_axi_myarr_BVALID;
    end else begin
        myarr_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((myarr_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (myarr_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (cmp_i3_reg_400 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_synth_tb_Pipeline_for_odd_fu_142_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (tmp_2_reg_381 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_synth_tb_Pipeline_for_even_fu_151_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (ap_phi_mux_is_sorted_phi_fu_129_p4 == 1'd1) & (icmp_ln16_2_fu_347_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if (((1'b1 == ap_CS_fsm_state13) & (ap_phi_mux_is_sorted_phi_fu_129_p4 == 1'd1) & (icmp_ln16_2_fu_347_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (myarr_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((1'b0 == ap_block_state22_on_subcall_done) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_1_fu_210_p2 = ($signed(sext_ln16_fu_185_p1) + $signed(33'd8589934591));

assign add_ln16_2_fu_255_p2 = (trunc_ln16_fu_251_p1 + 32'd2);

assign add_ln16_3_fu_285_p2 = (select_ln16_1_fu_261_p3 + 32'd2);

assign add_ln16_4_fu_291_p2 = (zext_ln16_fu_247_p1 + 64'd1);

assign add_ln16_5_fu_297_p2 = (zext_ln16_1_fu_281_p1 + 64'd1);

assign add_ln16_fu_188_p2 = ($signed(sext_ln16_fu_185_p1) + $signed(33'd1));

assign and_ln1_fu_331_p3 = {{tmp_1_fu_321_p4}, {1'd0}};

assign and_ln_fu_313_p3 = {{tmp_fu_303_p4}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state9 = ap_NS_fsm[32'd8];

always @ (*) begin
    ap_block_state22_on_subcall_done = ((grp_synth_tb_Pipeline_read_sorted_fu_162_ap_done == 1'b0) & (icmp_ln16_2_reg_424 == 1'd1));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i3_fu_222_p2 = (($signed(sub_i_reg_374) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start = grp_synth_tb_Pipeline_fill_unsorted_fu_136_ap_start_reg;

assign grp_synth_tb_Pipeline_for_even_fu_151_ap_start = grp_synth_tb_Pipeline_for_even_fu_151_ap_start_reg;

assign grp_synth_tb_Pipeline_for_odd_fu_142_ap_start = grp_synth_tb_Pipeline_for_odd_fu_142_ap_start_reg;

assign grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start = grp_synth_tb_Pipeline_read_sorted_fu_162_ap_start_reg;

assign icmp_ln16_1_fu_216_p2 = (($signed(add_ln16_fu_188_p2) > $signed(33'd2)) ? 1'b1 : 1'b0);

assign icmp_ln16_2_fu_347_p2 = (($signed(n) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_204_p2 = (($signed(tmp_3_fu_194_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign myarr_out = grp_synth_tb_Pipeline_read_sorted_fu_162_myarr_out;

assign myarr_out_ap_vld = grp_synth_tb_Pipeline_read_sorted_fu_162_myarr_out_ap_vld;

assign select_ln16_1_fu_261_p3 = ((icmp_ln16_1_reg_395[0:0] == 1'b1) ? sub_i_reg_374 : 32'd0);

assign select_ln16_fu_227_p3 = ((icmp_ln16_reg_385[0:0] == 1'b1) ? add_ln16_1_reg_390 : 33'd0);

assign sext_ln16_1_fu_243_p1 = $signed(trunc_ln16_2_fu_233_p4);

assign sext_ln16_2_fu_277_p1 = $signed(trunc_ln16_3_fu_267_p4);

assign sext_ln16_fu_185_p1 = sub_i_reg_374;

assign sub_i_fu_171_p2 = ($signed(n) + $signed(32'd4294967294));

assign tmp_1_fu_321_p4 = {{add_ln16_3_fu_285_p2[31:1]}};

assign tmp_3_fu_194_p4 = {{add_ln16_fu_188_p2[32:2]}};

assign tmp_fu_303_p4 = {{add_ln16_2_fu_255_p2[31:1]}};

assign trunc_ln16_1_fu_352_p1 = n[30:0];

assign trunc_ln16_2_fu_233_p4 = {{select_ln16_fu_227_p3[32:1]}};

assign trunc_ln16_3_fu_267_p4 = {{select_ln16_1_fu_261_p3[31:1]}};

assign trunc_ln16_fu_251_p1 = select_ln16_fu_227_p3[31:0];

assign zext_ln16_1_fu_281_p1 = $unsigned(sext_ln16_2_fu_277_p1);

assign zext_ln16_fu_247_p1 = $unsigned(sext_ln16_1_fu_243_p1);

always @ (posedge ap_clk) begin
    and_ln_reg_414[0] <= 1'b0;
    and_ln1_reg_419[0] <= 1'b0;
end

endmodule //synth_tb
